import type {
  Account,
  Transaction,
  CreditCard,
  StockHolding,
  MutualFund,
  NetWorthEntry,
} from "@/types";

export const mockAccounts: Account[] = [
  {
    id: "acc1",
    name: "HDFC Savings",
    type: "savings",
    balance: 125000,
    bankName: "HDFC Bank",
    lastFourDigits: "4521",
    color: "#6366f1",
  },
  {
    id: "acc2",
    name: "SBI Current",
    type: "current",
    balance: 87500,
    bankName: "State Bank of India",
    lastFourDigits: "8832",
    color: "#8b5cf6",
  },
  {
    id: "acc3",
    name: "Cash Wallet",
    type: "cash",
    balance: 8200,
    color: "#10b981",
  },
  {
    id: "acc4",
    name: "Paytm Wallet",
    type: "upi",
    balance: 3500,
    color: "#f59e0b",
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "t1",
    type: "income",
    amount: 85000,
    category: "salary",
    accountId: "acc1",
    date: "2026-05-01",
    notes: "May salary",
  },
  {
    id: "t2",
    type: "expense",
    amount: 3200,
    category: "food",
    accountId: "acc1",
    date: "2026-05-02",
    notes: "Groceries & dining",
  },
  {
    id: "t3",
    type: "expense",
    amount: 1500,
    category: "travel",
    accountId: "acc3",
    date: "2026-05-03",
    notes: "Cab & metro",
  },
  {
    id: "t4",
    type: "income",
    amount: 25000,
    category: "freelance",
    accountId: "acc1",
    date: "2026-05-05",
    notes: "Design project",
  },
  {
    id: "t5",
    type: "expense",
    amount: 12000,
    category: "shopping",
    accountId: "acc1",
    date: "2026-05-07",
    notes: "Amazon purchases",
  },
  {
    id: "t6",
    type: "expense",
    amount: 5500,
    category: "bills",
    accountId: "acc2",
    date: "2026-05-08",
    notes: "Electricity & internet",
  },
  {
    id: "t7",
    type: "expense",
    amount: 2200,
    category: "entertainment",
    accountId: "acc4",
    date: "2026-05-09",
    notes: "OTT subscriptions",
  },
  {
    id: "t8",
    type: "expense",
    amount: 18000,
    category: "emi",
    accountId: "acc1",
    date: "2026-05-10",
    notes: "Home loan EMI",
  },
  {
    id: "t9",
    type: "expense",
    amount: 3800,
    category: "health",
    accountId: "acc1",
    date: "2026-05-11",
    notes: "Medical checkup",
  },
  {
    id: "t10",
    type: "income",
    amount: 4200,
    category: "interest",
    accountId: "acc1",
    date: "2026-05-12",
    notes: "FD interest",
  },
  {
    id: "t11",
    type: "expense",
    amount: 4500,
    category: "fuel",
    accountId: "acc3",
    date: "2026-05-13",
    notes: "Petrol",
  },
  {
    id: "t12",
    type: "transfer",
    amount: 10000,
    category: "transfer",
    accountId: "acc1",
    toAccountId: "acc2",
    date: "2026-05-14",
    notes: "Transfer to current",
  },
  {
    id: "t13",
    type: "expense",
    amount: 2800,
    category: "food",
    accountId: "acc4",
    date: "2026-05-15",
    notes: "Zomato & Swiggy",
  },
  {
    id: "t14",
    type: "expense",
    amount: 15000,
    category: "investment",
    accountId: "acc1",
    date: "2026-05-16",
    notes: "SIP investment",
  },
  {
    id: "t15",
    type: "income",
    amount: 8000,
    category: "rental",
    accountId: "acc2",
    date: "2026-05-17",
    notes: "Rental income",
  },
];

export const mockCreditCards: CreditCard[] = [
  {
    id: "cc1",
    name: "HDFC Regalia",
    bankName: "HDFC Bank",
    lastFourDigits: "7823",
    creditLimit: 300000,
    outstandingAmount: 48500,
    billingCycleDay: 15,
    dueDate: "2026-06-05",
    color: "#6366f1",
  },
  {
    id: "cc2",
    name: "SBI Simply Click",
    bankName: "State Bank of India",
    lastFourDigits: "3341",
    creditLimit: 150000,
    outstandingAmount: 22000,
    billingCycleDay: 20,
    dueDate: "2026-06-10",
    color: "#8b5cf6",
  },
  {
    id: "cc3",
    name: "Axis Magnus",
    bankName: "Axis Bank",
    lastFourDigits: "9912",
    creditLimit: 500000,
    outstandingAmount: 95000,
    billingCycleDay: 1,
    dueDate: "2026-06-22",
    color: "#ec4899",
  },
];

export const mockStocks: StockHolding[] = [
  {
    id: "s1",
    name: "Reliance Industries",
    ticker: "RELIANCE",
    quantity: 50,
    avgBuyPrice: 2450,
    currentPrice: 2890,
    sector: "Energy",
  },
  {
    id: "s2",
    name: "Infosys",
    ticker: "INFY",
    quantity: 80,
    avgBuyPrice: 1380,
    currentPrice: 1520,
    sector: "IT",
  },
  {
    id: "s3",
    name: "HDFC Bank",
    ticker: "HDFCBANK",
    quantity: 45,
    avgBuyPrice: 1580,
    currentPrice: 1640,
    sector: "Banking",
  },
  {
    id: "s4",
    name: "Tata Consultancy",
    ticker: "TCS",
    quantity: 30,
    avgBuyPrice: 3450,
    currentPrice: 3820,
    sector: "IT",
  },
  {
    id: "s5",
    name: "Wipro",
    ticker: "WIPRO",
    quantity: 120,
    avgBuyPrice: 420,
    currentPrice: 395,
    sector: "IT",
  },
];

export const mockMutualFunds: MutualFund[] = [
  {
    id: "mf1",
    name: "Mirae Asset Large Cap Fund",
    type: "sip",
    units: 284.5,
    nav: 98.42,
    investedAmount: 24000,
    currentValue: 27999,
    category: "Large Cap",
  },
  {
    id: "mf2",
    name: "Axis Bluechip Fund",
    type: "sip",
    units: 190.2,
    nav: 62.18,
    investedAmount: 10000,
    currentValue: 11823,
    category: "Large Cap",
  },
  {
    id: "mf3",
    name: "Parag Parikh Flexi Cap",
    type: "lumpsum",
    units: 340.8,
    nav: 74.55,
    investedAmount: 20000,
    currentValue: 25399,
    category: "Flexi Cap",
  },
  {
    id: "mf4",
    name: "Quant Small Cap Fund",
    type: "sip",
    units: 98.6,
    nav: 212.4,
    investedAmount: 15000,
    currentValue: 20942,
    category: "Small Cap",
  },
];

export const mockNetWorth: NetWorthEntry[] = [
  { month: "Dec", netWorth: 620000, assets: 780000, liabilities: 160000 },
  { month: "Jan", netWorth: 648000, assets: 810000, liabilities: 162000 },
  { month: "Feb", netWorth: 675000, assets: 840000, liabilities: 165000 },
  { month: "Mar", netWorth: 710000, assets: 880000, liabilities: 170000 },
  { month: "Apr", netWorth: 742000, assets: 915000, liabilities: 173000 },
  { month: "May", netWorth: 785000, assets: 962000, liabilities: 177000 },
];
